#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import io
import json
import re
from pathlib import Path
from typing import Any

import requests
from pypdf import PdfReader


DECIMAL_PAIR_RE = re.compile(
    r"(?P<lat>[+-]?\d{1,2}\.\d{2,})\s*[,;/ ]\s*(?P<lon>[+-]?\d{1,3}\.\d{2,})"
)

DMS_PAIR_RE = re.compile(
    r"(?P<lat_deg>\d{1,2})[°\s]+(?P<lat_min>\d{1,2})['\s]+(?P<lat_sec>\d{1,2}(?:\.\d+)?)?[\"]?\s*(?P<lat_dir>[NS])"
    r"[\s,;/]+"
    r"(?P<lon_deg>\d{1,3})[°\s]+(?P<lon_min>\d{1,2})['\s]+(?P<lon_sec>\d{1,2}(?:\.\d+)?)?[\"]?\s*(?P<lon_dir>[EW])",
    re.IGNORECASE,
)


def dms_to_decimal(degrees: str, minutes: str, seconds: str | None, direction: str) -> float:
    value = int(degrees) + int(minutes) / 60.0 + (float(seconds) if seconds else 0.0) / 3600.0
    if direction.upper() in {"S", "W"}:
        value *= -1
    return round(value, 6)


def extract_coordinate_mentions(text: str) -> list[dict[str, Any]]:
    mentions: list[dict[str, Any]] = []
    for match in DECIMAL_PAIR_RE.finditer(text):
        lat = float(match.group("lat"))
        lon = float(match.group("lon"))
        if -90 <= lat <= 90 and -180 <= lon <= 180:
            mentions.append(
                {
                    "match_text": match.group(0),
                    "lat": round(lat, 6),
                    "lon": round(lon, 6),
                    "format": "decimal",
                }
            )
    for match in DMS_PAIR_RE.finditer(text):
        lat = dms_to_decimal(match.group("lat_deg"), match.group("lat_min"), match.group("lat_sec"), match.group("lat_dir"))
        lon = dms_to_decimal(match.group("lon_deg"), match.group("lon_min"), match.group("lon_sec"), match.group("lon_dir"))
        if -90 <= lat <= 90 and -180 <= lon <= 180:
            mentions.append(
                {
                    "match_text": match.group(0),
                    "lat": lat,
                    "lon": lon,
                    "format": "dms",
                }
            )
    unique = []
    seen = set()
    for item in mentions:
        key = (item["lat"], item["lon"], item["format"])
        if key not in seen:
            seen.add(key)
            unique.append(item)
    return unique


def text_snippet(text: str, needle: str, window: int = 120) -> str:
    idx = text.find(needle)
    if idx == -1:
        return ""
    start = max(0, idx - window)
    end = min(len(text), idx + len(needle) + window)
    return " ".join(text[start:end].split())


def fetch_pdf_text(url: str, session: requests.Session) -> str:
    response = session.get(url, timeout=45)
    response.raise_for_status()
    content = io.BytesIO(response.content)
    reader = PdfReader(content)
    text_parts = []
    for page in reader.pages:
        try:
            text_parts.append(page.extract_text() or "")
        except Exception:
            continue
    return "\n".join(text_parts)


def iter_rows(csv_paths: list[Path]) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for path in csv_paths:
        with path.open(newline="", encoding="utf-8") as handle:
            rows.extend(list(csv.DictReader(handle)))
    return rows


def main() -> None:
    parser = argparse.ArgumentParser(description="Download paper PDFs and extract coordinate mentions from full text.")
    parser.add_argument("csv_files", nargs="+", help="Paper CSVs generated by the academic extractor.")
    parser.add_argument("--limit", type=int, default=8, help="Maximum papers to fetch.")
    parser.add_argument("--output-prefix", default="pdf_extract", help="Output prefix.")
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    csv_paths = [Path(p) if Path(p).is_absolute() else root / p for p in args.csv_files]
    rows = iter_rows(csv_paths)
    pdf_rows = [row for row in rows if row.get("pdf_url")]

    session = requests.Session()
    session.headers.update({"User-Agent": "arkhub-pdf-extractor/0.1"})

    processed = []
    mentions = []
    for row in pdf_rows[: args.limit]:
        title = row["title"]
        url = row["pdf_url"]
        try:
            text = fetch_pdf_text(url, session)
            coords = extract_coordinate_mentions(text)
            processed.append(
                {
                    "title": title,
                    "year": row.get("year", ""),
                    "doi": row.get("doi", ""),
                    "pdf_url": url,
                    "coordinate_mentions": len(coords),
                }
            )
            for item in coords:
                mentions.append(
                    {
                        "title": title,
                        "year": row.get("year", ""),
                        "doi": row.get("doi", ""),
                        "pdf_url": url,
                        "lat": item["lat"],
                        "lon": item["lon"],
                        "format": item["format"],
                        "match_text": item["match_text"],
                        "context": text_snippet(text, item["match_text"]),
                    }
                )
        except Exception as exc:
            processed.append(
                {
                    "title": title,
                    "year": row.get("year", ""),
                    "doi": row.get("doi", ""),
                    "pdf_url": url,
                    "coordinate_mentions": "",
                    "error": str(exc),
                }
            )

    out_dir = root / "data" / "interim" / "academic"
    out_dir.mkdir(parents=True, exist_ok=True)
    processed_path = out_dir / f"{args.output_prefix}_pdf_scan.json"
    mentions_path = out_dir / f"{args.output_prefix}_pdf_coordinate_mentions.csv"

    with processed_path.open("w", encoding="utf-8") as handle:
        json.dump(processed, handle, indent=2, ensure_ascii=True)

    with mentions_path.open("w", encoding="utf-8", newline="") as handle:
        if mentions:
            writer = csv.DictWriter(handle, fieldnames=list(mentions[0].keys()))
            writer.writeheader()
            writer.writerows(mentions)
        else:
            handle.write("")

    print(f"processed_json: {processed_path}")
    print(f"mentions_csv: {mentions_path}")
    print(f"papers_scanned: {len(processed)}")
    print(f"mentions_found: {len(mentions)}")


if __name__ == "__main__":
    main()
